CREATE TABLE `references` (
	`id` text PRIMARY KEY NOT NULL,
	`title` text NOT NULL,
	`source_url` text NOT NULL,
	`canonical_url` text,
	`site_name` text,
	`author` text,
	`preview_url` text,
	`media_type` text NOT NULL,
	`asset_category` text NOT NULL,
	`source_category` text,
	`style_tags` text DEFAULT '[]' NOT NULL,
	`use_tags` text DEFAULT '[]' NOT NULL,
	`license_status` text NOT NULL,
	`attribution_text` text,
	`public_status` text NOT NULL,
	`rating` integer,
	`inspiration_points` text DEFAULT '[]' NOT NULL,
	`deconstruction_notes` text,
	`transformation_ideas` text,
	`avoid_copying_notes` text,
	`related_original_asset` text,
	`created_at` text NOT NULL,
	`updated_at` text NOT NULL
);
