import {
  AssetCategory,
  LicenseStatus,
  MediaType,
  PublicStatus,
  QualityStatus,
} from "./reference";

export const LANGUAGES = ["zh", "en"] as const;

export type Language = (typeof LANGUAGES)[number];

const assetCategoryLabels: Record<Language, Record<AssetCategory, string>> = {
  zh: {
    character: "角色",
    environment: "环境",
    prop: "道具",
    ui_hud: "界面/HUD",
    vfx: "特效",
    material_texture: "材质",
    animation: "动画",
    audio: "音频",
  },
  en: {
    character: "Character",
    environment: "Environment",
    prop: "Prop",
    ui_hud: "UI/HUD",
    vfx: "VFX",
    material_texture: "Material",
    animation: "Animation",
    audio: "Audio",
  },
};

const mediaTypeLabels: Record<Language, Record<MediaType, string>> = {
  zh: {
    image: "图片",
    video: "视频",
    audio: "音频",
    model: "模型",
    article: "文章",
    asset_pack: "素材包",
    screenshot: "截图",
    mixed: "混合",
  },
  en: {
    image: "image",
    video: "video",
    audio: "audio",
    model: "model",
    article: "article",
    asset_pack: "asset pack",
    screenshot: "screenshot",
    mixed: "mixed",
  },
};

const licenseStatusLabels: Record<Language, Record<LicenseStatus, string>> = {
  zh: {
    private_reference: "私有参考",
    unknown_license: "授权未知",
    source_link_only: "仅保留来源链接",
    attribution_required: "需要署名",
    cc0_or_public_domain: "CC0 或公有领域",
    permission_granted: "已获许可",
  },
  en: {
    private_reference: "private reference",
    unknown_license: "unknown license",
    source_link_only: "source link only",
    attribution_required: "attribution required",
    cc0_or_public_domain: "cc0 or public domain",
    permission_granted: "permission granted",
  },
};

const publicStatusLabels: Record<Language, Record<PublicStatus, string>> = {
  zh: {
    private: "私有",
    review: "待复核",
    public_safe: "可安全公开",
    public_link_only: "仅公开链接",
  },
  en: {
    private: "private",
    review: "review",
    public_safe: "public safe",
    public_link_only: "public link only",
  },
};

const qualityStatusLabels: Record<Language, Record<QualityStatus, string>> = {
  zh: {
    captured: "已捕获",
    needs_analysis: "待分析",
    analyzed: "已分析",
    ready_for_use: "可用于创作",
    blocked: "已阻塞",
  },
  en: {
    captured: "captured",
    needs_analysis: "needs analysis",
    analyzed: "analyzed",
    ready_for_use: "ready for use",
    blocked: "blocked",
  },
};

const copy = {
  zh: {
    languageLabel: "语言",
    chinese: "中文",
    english: "English",
    productDescription: "私有游戏素材参考研究台，用来把参考来源转化为原创创作原则。",
    filtersLabel: "参考筛选",
    workspaceMode: "灵感提炼工作台",
    sourceAndSafety: "来源与安全",
    scoreMatrix: "评分矩阵",
    tagAxes: "标签轴",
    researchControls: "研究控制",
    referenceDeck: "参考卡组",
    inspirationWorkbench: "灵感提炼",
    privateByDefault: "私有默认",
    assetCategory: "资产分类",
    allCategories: "全部分类",
    publicStatus: "公开状态",
    allStatuses: "全部状态",
    qualityStatus: "质量状态",
    allQualityStatuses: "全部质量状态",
    licenseStatus: "授权状态",
    allLicenses: "全部授权",
    clearFilters: "清除筛选",
    search: "搜索",
    searchPlaceholder: "标题、来源、标签、笔记...",
    addReference: "+ 添加参考",
    sourceUrl: "来源链接",
    title: "标题",
    site: "站点",
    author: "作者",
    mediaType: "媒体类型",
    styleTags: "风格标签",
    styleTagsPlaceholder: "像素、舒适、科幻",
    useTags: "用途标签",
    useTagsPlaceholder: "战斗反馈、背包界面",
    mechanicTags: "机制标签",
    mechanicTagsPlaceholder: "制作、战斗、导航",
    moodTags: "情绪标签",
    moodTagsPlaceholder: "温暖、紧张、神秘",
    visualLanguageTags: "视觉语言标签",
    visualLanguageTagsPlaceholder: "轮廓、对比、材质逻辑",
    inspirationPoints: "灵感要点",
    inspirationPointsPlaceholder: "用逗号分隔可复用想法",
    deconstructionNotes: "拆解笔记",
    transformationIdeas: "转化思路",
    avoidCopying: "避免复制",
    previewingMetadata: "正在预览...",
    previewMetadata: "预览元数据",
    savePrivateReference: "保存为私有参考",
    references: "条参考",
    safetySummary: "打开详情前即可看到安全状态",
    noReferencesMatch: "没有符合筛选的参考",
    noReferencesHint: "清除筛选或添加一条新的私有参考继续验证。",
    unknownSource: "未知来源",
    selectedReference: "选中的参考",
    openSource: "打开来源",
    edit: "编辑",
    source: "来源",
    canonicalUrl: "规范链接",
    previewUrl: "预览图链接",
    sourceCategory: "来源分类",
    classificationAndSafety: "分类与安全",
    attributionText: "署名文本",
    inspiration: "灵感",
    rating: "评分",
    scoreSummary: "评分摘要",
    referenceValueScore: "参考价值",
    transformabilityScore: "可转化性",
    copyrightRiskScore: "版权风险",
    productionReadinessScore: "制作就绪度",
    structuredInspiration: "结构化灵感",
    addInspirationEntry: "+ 添加灵感条目",
    removeInspirationEntry: "移除条目",
    inspirationObservation: "观察",
    inspirationPrinciple: "原则",
    inspirationTransferableIdea: "可迁移想法",
    inspirationOriginalApplication: "原创应用",
    inspirationAvoidCopying: "避免复制",
    emptyInspirationEntries: "还没有结构化灵感条目。",
    relatedOriginalAsset: "关联原创资产",
    saveChanges: "保存修改",
    saving: "保存中...",
    cancel: "取消",
    unknown: "未知",
    media: "媒体",
    license: "授权",
    public: "公开",
    defaultAvoidCopying: "记录哪些具体表达不应被复制。",
    defaultInspiration: "添加这条参考能提供的具体原则。",
    deleteReference: "删除参考",
    deleting: "删除中...",
    noReferenceSelected: "未选择参考",
    noReferenceHint: "添加或选择一条参考，查看来源、安全和灵感字段。",
    metadataPreviewSuccess: "元数据预览已就绪。保存前请检查字段。",
    metadataPreviewFailure: "元数据预览失败。你仍然可以手动保存这条参考。",
    metadataPreviewLoading: "正在预览元数据...",
    seedFallback: "正在显示入门示例。添加一条私有参考后即可开始使用自己的数据集。",
    pasteSourceUrl: "请先粘贴来源链接，再预览元数据。",
    metadataPreviewFailedFallback: "元数据预览失败。你仍然可以手动保存这条参考。",
    saveFailed: "保存失败。表单内容已保留。",
    saveFailedShort: "保存失败。",
    savedPrivate: "已按私有默认状态保存参考。",
    editingSelected: "正在编辑选中的参考。",
    editCanceled: "已取消编辑；没有保存修改。",
    selectionChanged: "选择已切换；编辑草稿已关闭。",
    selectionHidden: "当前筛选隐藏了选中项；编辑草稿已关闭。",
    finishSaving: "请先完成保存，再切换选择。",
    noChanges: "没有需要保存的修改。",
    savingChanges: "正在保存参考修改...",
    starterUpdatedLocally: "入门示例已在本地更新；D1 未变更。",
    changesSaved: "参考修改已保存。",
    updateFailed: "更新失败。编辑内容已保留。",
    deleteFailed: "删除失败。",
    deleted: "参考已删除。",
  },
  en: {
    languageLabel: "Language",
    chinese: "中文",
    english: "English",
    productDescription: "Private research desk for turning game asset references into original creative principles.",
    filtersLabel: "Reference filters",
    workspaceMode: "Inspiration workbench",
    sourceAndSafety: "Source and safety",
    scoreMatrix: "Score matrix",
    tagAxes: "Tag axes",
    researchControls: "Research controls",
    referenceDeck: "Reference deck",
    inspirationWorkbench: "Inspiration workbench",
    privateByDefault: "Private by default",
    assetCategory: "Asset category",
    allCategories: "All categories",
    publicStatus: "Public status",
    allStatuses: "All statuses",
    qualityStatus: "Quality status",
    allQualityStatuses: "All quality statuses",
    licenseStatus: "License status",
    allLicenses: "All licenses",
    clearFilters: "Clear filters",
    search: "Search",
    searchPlaceholder: "Title, source, tag, note...",
    addReference: "+ Add reference",
    sourceUrl: "Source URL",
    title: "Title",
    site: "Site",
    author: "Author",
    mediaType: "Media type",
    styleTags: "Style tags",
    styleTagsPlaceholder: "pixel, cozy, sci-fi",
    useTags: "Use tags",
    useTagsPlaceholder: "combat feedback, inventory",
    mechanicTags: "Mechanic tags",
    mechanicTagsPlaceholder: "crafting, combat, navigation",
    moodTags: "Mood tags",
    moodTagsPlaceholder: "warm, tense, mysterious",
    visualLanguageTags: "Visual language tags",
    visualLanguageTagsPlaceholder: "silhouette, contrast, material logic",
    inspirationPoints: "Inspiration points",
    inspirationPointsPlaceholder: "Comma-separated useful ideas",
    deconstructionNotes: "Deconstruction notes",
    transformationIdeas: "Transformation ideas",
    avoidCopying: "Avoid copying",
    previewingMetadata: "Previewing...",
    previewMetadata: "Preview metadata",
    savePrivateReference: "Save private reference",
    references: "references",
    safetySummary: "Safety status stays visible before opening details",
    noReferencesMatch: "No references match these filters",
    noReferencesHint: "Clear filters or add a new private reference to continue validation.",
    unknownSource: "Unknown source",
    selectedReference: "Selected reference",
    openSource: "Open source",
    edit: "Edit",
    source: "Source",
    canonicalUrl: "Canonical URL",
    previewUrl: "Preview URL",
    sourceCategory: "Source category",
    classificationAndSafety: "Classification and safety",
    attributionText: "Attribution text",
    inspiration: "Inspiration",
    rating: "Rating",
    scoreSummary: "Score summary",
    referenceValueScore: "Reference value",
    transformabilityScore: "Transformability",
    copyrightRiskScore: "Copyright risk",
    productionReadinessScore: "Production readiness",
    structuredInspiration: "Structured inspiration",
    addInspirationEntry: "+ Add inspiration entry",
    removeInspirationEntry: "Remove entry",
    inspirationObservation: "Observation",
    inspirationPrinciple: "Principle",
    inspirationTransferableIdea: "Transferable idea",
    inspirationOriginalApplication: "Original application",
    inspirationAvoidCopying: "Avoid copying",
    emptyInspirationEntries: "No structured inspiration entries yet.",
    relatedOriginalAsset: "Related original asset",
    saveChanges: "Save changes",
    saving: "Saving...",
    cancel: "Cancel",
    unknown: "Unknown",
    media: "Media",
    license: "License",
    public: "Public",
    defaultAvoidCopying: "Record what exact expression should not be copied.",
    defaultInspiration: "Add concrete principles this reference teaches.",
    deleteReference: "Delete reference",
    deleting: "Deleting...",
    noReferenceSelected: "No reference selected",
    noReferenceHint: "Add or select a reference to review source, safety, and inspiration fields.",
    metadataPreviewSuccess: "Metadata preview ready. Review the fields before saving.",
    metadataPreviewFailure: "Metadata preview failed. You can still save this reference manually.",
    metadataPreviewLoading: "Previewing metadata...",
    seedFallback: "Showing starter examples. Add a private reference to begin using your own dataset.",
    pasteSourceUrl: "Paste a source URL before previewing metadata.",
    metadataPreviewFailedFallback: "Metadata preview failed. You can still save this reference manually.",
    saveFailed: "Save failed. Form contents were preserved.",
    saveFailedShort: "Save failed.",
    savedPrivate: "Reference saved privately by default.",
    editingSelected: "Editing selected reference.",
    editCanceled: "Edit canceled; no changes saved.",
    selectionChanged: "Selection changed; edit draft was closed.",
    selectionHidden: "Selection no longer visible; edit draft was closed.",
    finishSaving: "Finish saving before changing selection.",
    noChanges: "No changes to save.",
    savingChanges: "Saving reference changes...",
    starterUpdatedLocally: "Starter example updated locally; D1 was not changed.",
    changesSaved: "Reference changes saved.",
    updateFailed: "Update failed. Edit contents were preserved.",
    deleteFailed: "Delete failed.",
    deleted: "Reference deleted.",
  },
} satisfies Record<Language, Record<string, string>>;

export function uiCopy(language: Language = "zh") {
  return copy[language];
}

export function labelForAssetCategory(value: AssetCategory, language: Language = "zh") {
  return assetCategoryLabels[language][value];
}

export function labelForMediaType(value: MediaType, language: Language = "zh") {
  return mediaTypeLabels[language][value];
}

export function labelForLicenseStatus(value: LicenseStatus, language: Language = "zh") {
  return licenseStatusLabels[language][value];
}

export function labelForPublicStatus(value: PublicStatus, language: Language = "zh") {
  return publicStatusLabels[language][value];
}

export function labelForQualityStatus(value: QualityStatus, language: Language = "zh") {
  return qualityStatusLabels[language][value];
}
