import {
  AssetCategory,
  LicenseStatus,
  MediaType,
  PublicStatus,
  QualityStatus,
} from "./reference";
import type { SynthesisStatus } from "./synthesis";

export const LANGUAGES = ["zh", "en"] as const;

export type Language = (typeof LANGUAGES)[number];

const assetCategoryLabels: Record<Language, Record<AssetCategory, string>> = {
  zh: {
    character: "角色",
    environment: "环境",
    prop: "道具",
    ui_hud: "界面/HUD",
    vfx: "特效",
    material_texture: "材质",
    animation: "动画",
    audio: "音频",
  },
  en: {
    character: "Character",
    environment: "Environment",
    prop: "Prop",
    ui_hud: "UI/HUD",
    vfx: "VFX",
    material_texture: "Material",
    animation: "Animation",
    audio: "Audio",
  },
};

const mediaTypeLabels: Record<Language, Record<MediaType, string>> = {
  zh: {
    image: "图片",
    video: "视频",
    audio: "音频",
    model: "模型",
    article: "文章",
    asset_pack: "素材包",
    screenshot: "截图",
    mixed: "混合",
  },
  en: {
    image: "image",
    video: "video",
    audio: "audio",
    model: "model",
    article: "article",
    asset_pack: "asset pack",
    screenshot: "screenshot",
    mixed: "mixed",
  },
};

const licenseStatusLabels: Record<Language, Record<LicenseStatus, string>> = {
  zh: {
    private_reference: "私有参考",
    unknown_license: "授权未知",
    source_link_only: "仅保留来源链接",
    attribution_required: "需要署名",
    cc0_or_public_domain: "CC0 或公有领域",
    permission_granted: "已获许可",
  },
  en: {
    private_reference: "private reference",
    unknown_license: "unknown license",
    source_link_only: "source link only",
    attribution_required: "attribution required",
    cc0_or_public_domain: "cc0 or public domain",
    permission_granted: "permission granted",
  },
};

const publicStatusLabels: Record<Language, Record<PublicStatus, string>> = {
  zh: {
    private: "私有",
    review: "待复核",
    public_safe: "可安全公开",
    public_link_only: "仅公开链接",
  },
  en: {
    private: "private",
    review: "review",
    public_safe: "public safe",
    public_link_only: "public link only",
  },
};

const qualityStatusLabels: Record<Language, Record<QualityStatus, string>> = {
  zh: {
    captured: "已捕获",
    needs_analysis: "待分析",
    analyzed: "已分析",
    ready_for_use: "可用于创作",
    blocked: "已阻塞",
  },
  en: {
    captured: "captured",
    needs_analysis: "needs analysis",
    analyzed: "analyzed",
    ready_for_use: "ready for use",
    blocked: "blocked",
  },
};

const synthesisStatusLabels: Record<Language, Record<SynthesisStatus, string>> = {
  zh: {
    draft: "草稿",
    actionable: "可执行",
    archived: "已归档",
  },
  en: {
    draft: "Draft",
    actionable: "Actionable",
    archived: "Archived",
  },
};

const copy = {
  zh: {
    languageLabel: "语言",
    chinese: "中文",
    english: "English",
    productDescription: "私有游戏素材参考研究台，用来把参考来源转化为原创创作原则。",
    filtersLabel: "参考筛选",
    workspaceMode: "灵感提炼工作台",
    sourceAndSafety: "来源与安全",
    scoreMatrix: "评分矩阵",
    tagAxes: "标签轴",
    researchControls: "研究控制",
    referenceDeck: "参考卡组",
    inspirationWorkbench: "灵感提炼",
    referencesView: "参考",
    synthesesView: "综合稿",
    startComparison: "开始对比",
    cancelComparison: "取消对比",
    enterSynthesis: "进入综合稿",
    comparisonCount: "已选择 {count} / 4",
    selectedForComparison: "已选择",
    discardReferenceEditTitle: "未保存的参考编辑",
    discardReferenceEditConfirmation: "开始对比会丢弃当前参考的未保存修改，是否继续？",
    discardReferenceEditAndCompare: "丢弃修改并开始对比",
    synthesisWorkspace: "综合稿工作区",
    syntheses: "综合稿",
    createSynthesis: "新建综合稿",
    noSyntheses: "还没有综合稿。",
    synthesisTitle: "综合稿标题",
    targetAsset: "目标资产",
    sharedPrinciples: "共同原则",
    keyDifferences: "关键差异",
    originalDirection: "原创方向",
    synthesisAvoidCopying: "避免复制",
    designConstraints: "设计约束",
    experimentPlan: "实验计划",
    nextActions: "下一步行动",
    additionalNotes: "补充备注",
    synthesisStatus: "综合稿状态",
    synthesisStatusFilter: "按状态筛选",
    allSynthesisStatuses: "全部综合稿状态",
    staleReference: "参考快照已过期",
    unavailableReference: "来源已不可用；历史快照仍保留。",
    refreshSnapshot: "刷新快照",
    refreshingSnapshot: "正在刷新快照...",
    saveSynthesis: "保存综合稿",
    savingSynthesis: "正在保存综合稿...",
    synthesisSaved: "综合稿已保存。",
    synthesisSaveFailed: "综合稿保存失败；草稿内容已保留。",
    reselectSynthesisReferences: "返回参考并重新选择",
    synthesisValidationFailed: "请检查综合稿标题、状态和字段长度后重试。",
    synthesisReferencesChanged: "所选参考已发生变化；草稿已保留，请返回参考并重新选择。",
    synthesisRelationNotFound: "这条综合稿参考关系已不存在，请重新打开综合稿。",
    synthesisReferenceUnavailable: "当前参考已不可用，旧快照保持不变。",
    synthesisNotFound: "综合稿已不存在或无法读取。",
    synthesisMigrationRequired: "综合稿数据尚未就绪，请完成数据库迁移后重试。",
    synthesisOperationFailed: "综合稿操作失败，请稍后重试。",
    unsavedChanges: "有未保存修改",
    unsavedChangesConfirmation: "仍有未保存修改，确定要离开吗？",
    deleteSynthesis: "删除综合稿",
    deleteSynthesisConfirmation: "确定删除这份综合稿吗？此操作无法撤销。",
    synthesisDeleted: "综合稿已删除。",
    synthesisDeleteFailed: "综合稿删除失败。",
    exportSynthesisMarkdown: "导出综合稿 Markdown",
    synthesisExportWarning: "导出内容包含未保存修改，仅供当前研究记录使用。",
    privateByDefault: "私有默认",
    sortBy: "排序",
    sortUpdated: "最近更新",
    sortReferenceValue: "参考价值",
    sortTransformability: "可转化性",
    sortCopyrightRisk: "版权风险最低",
    sortProductionReadiness: "制作就绪度",
    sortTitle: "标题",
    pinReference: "置顶参考",
    unpinReference: "取消置顶",
    pinned: "已置顶",
    exportMarkdown: "导出 Markdown",
    exportJson: "导出 JSON",
    dataManagement: "数据管理",
    closeDataManagement: "关闭数据管理",
    backupTab: "备份",
    restoreTab: "恢复",
    fullBackup: "导出完整备份",
    exportingBackup: "正在导出备份...",
    includeDevicePreferences: "包含本设备偏好",
    transparentJsonWarning: "透明 JSON 可能包含私有来源和研究笔记。",
    chooseBackupFile: "选择备份文件",
    changeBackupFile: "更换文件",
    backupFileDetails: "文件信息",
    backupVersion: "备份版本",
    backupExportedAt: "导出时间",
    previewBackup: "预览恢复",
    previewingBackup: "正在预览...",
    restoreBackup: "恢复数据",
    restoringBackup: "正在恢复...",
    retryRestore: "重新尝试",
    restoreDevicePreferences: "恢复本设备偏好",
    confirmOverwrite: "我确认用备份内容覆盖同 ID 的现有记录。",
    unsavedDraftRestoreTitle: "未保存草稿",
    unsavedDraftRestoreBody: "恢复会放弃当前未保存的草稿。",
    discardDraftAndRestore: "放弃草稿并恢复",
    restoreSucceeded: "研究数据已恢复。",
    preferencesRestoreApplied: "设备偏好已恢复。",
    preferencesRestoreFailed: "研究数据已恢复，但设备偏好未能写入。",
    backupReferences: "参考",
    backupSyntheses: "综合稿",
    backupRelations: "关联",
    backupHistoricalSnapshots: "历史快照",
    backupIssues: "校验问题",
    backupCreate: "新增",
    backupOverwrite: "覆盖",
    backupPreserve: "保留",
    backupInvalidJson: "文件不是有效的 JSON 备份。",
    backupUnsupportedFormat: "该文件不是 RefForge Backup。",
    backupUnsupportedVersion: "该备份版本暂不受支持。",
    backupTooLarge: "备份文件或记录数量超过 5 MB 限制。",
    backupValidationFailed: "备份内容未通过完整性校验。",
    backupChanged: "备份文件在预览后发生变化，请重新选择并预览。",
    backupPreviewStale: "研究数据在预览后发生变化，请重新预览。",
    backupOverwriteConfirmationRequired: "请确认覆盖现有记录后再恢复。",
    backupRestoreFailed: "恢复未完成，当前研究数据未被部分写入。",
    backupDatabaseUnavailable: "备份服务暂不可用，请稍后重试。",
    backupOperationFailed: "备份操作未完成，请稍后重试。",
    exportUnavailable: "请选择一条参考后再导出。",
    inspirationEntryCount: "结构化灵感条目",
    reviewQueue: "整理队列",
    queueAll: "全部参考",
    queueIncomplete: "待补全",
    queuePinned: "已置顶",
    queueHighValue: "高价值",
    queueLowRisk: "低版权风险",
    queueProductionReady: "可制作",
    qualityChecklist: "质量清单",
    qualityGuidedEditing: "补全导航",
    qualityGuidedPosition: "当前项",
    previousQualityIssue: "上一项",
    nextQualityIssue: "下一项",
    completeQualityIssue: "补全",
    qualityTargetMissing: "未找到对应编辑字段；草稿已保留。",
    qualityComplete: "资料完整",
    resizeFiltersPanel: "调整筛选面板宽度",
    resizeDetailsPanel: "调整详情面板宽度",
    collapseFiltersPanel: "收起筛选面板",
    expandFiltersPanel: "展开筛选面板",
    collapseDetailsPanel: "收起详情面板",
    expandDetailsPanel: "展开详情面板",
    resetPanelWidth: "双击恢复默认宽度",
    qualityIssueCount: "待补全",
    qualityPositiveSignals: "优势信号",
    qualitySourceGroup: "来源信息",
    qualitySafetyGroup: "安全信息",
    qualityInspirationGroup: "灵感信息",
    qualityScoresGroup: "评分信息",
    qualityMissingSite: "补充站点",
    qualityMissingAuthor: "补充作者",
    qualityMissingLicense: "确认授权",
    qualityMissingAttribution: "补充署名",
    qualityMissingAvoidCopying: "补充避免复制说明",
    qualityMissingInspirationPoints: "补充灵感要点",
    qualityMissingInspirationEntries: "补充结构化灵感",
    qualityMissingDeconstruction: "补充拆解笔记",
    qualityMissingTransformation: "补充转化思路",
    qualityMissingRating: "补充评分",
    qualityMissingReferenceValue: "补充参考价值",
    qualityMissingTransformability: "补充可转化性",
    qualityMissingCopyrightRisk: "补充版权风险",
    qualityMissingProductionReadiness: "补充制作就绪度",
    qualityBadgeHighValue: "高价值",
    qualityBadgeLowRisk: "低风险",
    qualityBadgeProductionReady: "可制作",
    qualityBadgeTransformable: "可转化",
    qualityBadgeAnalyzed: "已分析",
    assetCategory: "资产分类",
    allCategories: "全部分类",
    publicStatus: "公开状态",
    allStatuses: "全部状态",
    qualityStatus: "质量状态",
    allQualityStatuses: "全部质量状态",
    licenseStatus: "授权状态",
    allLicenses: "全部授权",
    clearFilters: "清除筛选",
    search: "搜索",
    searchPlaceholder: "标题、来源、标签、笔记...",
    addReference: "+ 添加参考",
    sourceUrl: "来源链接",
    title: "标题",
    site: "站点",
    author: "作者",
    mediaType: "媒体类型",
    styleTags: "风格标签",
    styleTagsPlaceholder: "像素、舒适、科幻",
    useTags: "用途标签",
    useTagsPlaceholder: "战斗反馈、背包界面",
    mechanicTags: "机制标签",
    mechanicTagsPlaceholder: "制作、战斗、导航",
    moodTags: "情绪标签",
    moodTagsPlaceholder: "温暖、紧张、神秘",
    visualLanguageTags: "视觉语言标签",
    visualLanguageTagsPlaceholder: "轮廓、对比、材质逻辑",
    inspirationPoints: "灵感要点",
    inspirationPointsPlaceholder: "用逗号分隔可复用想法",
    deconstructionNotes: "拆解笔记",
    transformationIdeas: "转化思路",
    avoidCopying: "避免复制",
    previewingMetadata: "正在预览...",
    previewMetadata: "预览元数据",
    savePrivateReference: "保存为私有参考",
    references: "条参考",
    safetySummary: "打开详情前即可看到安全状态",
    noReferencesMatch: "没有符合筛选的参考",
    noReferencesHint: "清除筛选或添加一条新的私有参考继续验证。",
    unknownSource: "未知来源",
    selectedReference: "选中的参考",
    openSource: "打开来源",
    edit: "编辑",
    source: "来源",
    canonicalUrl: "规范链接",
    previewUrl: "预览图链接",
    sourceCategory: "来源分类",
    classificationAndSafety: "分类与安全",
    attributionText: "署名文本",
    inspiration: "灵感",
    rating: "评分",
    scoreSummary: "评分摘要",
    referenceValueScore: "参考价值",
    transformabilityScore: "可转化性",
    copyrightRiskScore: "版权风险",
    productionReadinessScore: "制作就绪度",
    structuredInspiration: "结构化灵感",
    addInspirationEntry: "+ 添加灵感条目",
    removeInspirationEntry: "移除条目",
    inspirationObservation: "观察",
    inspirationPrinciple: "原则",
    inspirationTransferableIdea: "可迁移想法",
    inspirationOriginalApplication: "原创应用",
    inspirationAvoidCopying: "避免复制",
    emptyInspirationEntries: "还没有结构化灵感条目。",
    relatedOriginalAsset: "关联原创资产",
    saveChanges: "保存修改",
    saving: "保存中...",
    cancel: "取消",
    unknown: "未知",
    media: "媒体",
    license: "授权",
    public: "公开",
    defaultAvoidCopying: "记录哪些具体表达不应被复制。",
    defaultInspiration: "添加这条参考能提供的具体原则。",
    deleteReference: "删除参考",
    deleting: "删除中...",
    noReferenceSelected: "未选择参考",
    noReferenceHint: "添加或选择一条参考，查看来源、安全和灵感字段。",
    metadataPreviewSuccess: "元数据预览已就绪。保存前请检查字段。",
    metadataPreviewFailure: "元数据预览失败。你仍然可以手动保存这条参考。",
    metadataPreviewLoading: "正在预览元数据...",
    seedFallback: "正在显示入门示例。添加一条私有参考后即可开始使用自己的数据集。",
    pasteSourceUrl: "请先粘贴来源链接，再预览元数据。",
    metadataPreviewFailedFallback: "元数据预览失败。你仍然可以手动保存这条参考。",
    saveFailed: "保存失败。表单内容已保留。",
    saveFailedShort: "保存失败。",
    savedPrivate: "已按私有默认状态保存参考。",
    editingSelected: "正在编辑选中的参考。",
    editCanceled: "已取消编辑；没有保存修改。",
    selectionChanged: "选择已切换；编辑草稿已关闭。",
    selectionHidden: "当前筛选隐藏了选中项；编辑草稿已关闭。",
    finishSaving: "请先完成保存，再切换选择。",
    noChanges: "没有需要保存的修改。",
    savingChanges: "正在保存参考修改...",
    starterUpdatedLocally: "入门示例已在本地更新；D1 未变更。",
    changesSaved: "参考修改已保存。",
    updateFailed: "更新失败。编辑内容已保留。",
    deleteFailed: "删除失败。",
    deleted: "参考已删除。",
  },
  en: {
    languageLabel: "Language",
    chinese: "中文",
    english: "English",
    productDescription: "Private research desk for turning game asset references into original creative principles.",
    filtersLabel: "Reference filters",
    workspaceMode: "Inspiration workbench",
    sourceAndSafety: "Source and safety",
    scoreMatrix: "Score matrix",
    tagAxes: "Tag axes",
    researchControls: "Research controls",
    referenceDeck: "Reference deck",
    inspirationWorkbench: "Inspiration workbench",
    referencesView: "References",
    synthesesView: "Syntheses",
    startComparison: "Start comparison",
    cancelComparison: "Cancel comparison",
    enterSynthesis: "Enter synthesis",
    comparisonCount: "{count} / 4 selected",
    selectedForComparison: "Selected",
    discardReferenceEditTitle: "Unsaved reference edits",
    discardReferenceEditConfirmation: "Starting a comparison will discard the unsaved reference edits. Continue?",
    discardReferenceEditAndCompare: "Discard edits and compare",
    synthesisWorkspace: "Synthesis workspace",
    syntheses: "Syntheses",
    createSynthesis: "New synthesis",
    noSyntheses: "No syntheses yet.",
    synthesisTitle: "Synthesis title",
    targetAsset: "Target asset",
    sharedPrinciples: "Shared principles",
    keyDifferences: "Key differences",
    originalDirection: "Original direction",
    synthesisAvoidCopying: "Avoid copying",
    designConstraints: "Design constraints",
    experimentPlan: "Experiment plan",
    nextActions: "Next actions",
    additionalNotes: "Additional notes",
    synthesisStatus: "Synthesis status",
    synthesisStatusFilter: "Filter by status",
    allSynthesisStatuses: "All synthesis statuses",
    staleReference: "Reference snapshot is stale",
    unavailableReference: "Source unavailable; historical snapshot retained.",
    refreshSnapshot: "Refresh snapshot",
    refreshingSnapshot: "Refreshing snapshot...",
    saveSynthesis: "Save synthesis",
    savingSynthesis: "Saving synthesis...",
    synthesisSaved: "Synthesis saved.",
    synthesisSaveFailed: "Synthesis save failed; draft contents were preserved.",
    reselectSynthesisReferences: "Return to references and reselect",
    synthesisValidationFailed: "Check the synthesis title, status, and field lengths, then try again.",
    synthesisReferencesChanged: "The selected references changed. Your draft is preserved; return and reselect them.",
    synthesisRelationNotFound: "This synthesis reference relation no longer exists. Reopen the synthesis.",
    synthesisReferenceUnavailable: "The current reference is unavailable. The previous snapshot was kept.",
    synthesisNotFound: "The synthesis no longer exists or could not be read.",
    synthesisMigrationRequired: "Synthesis data is not ready. Apply the database migration and try again.",
    synthesisOperationFailed: "The synthesis operation failed. Try again shortly.",
    unsavedChanges: "Unsaved changes",
    unsavedChangesConfirmation: "You have unsaved changes. Leave anyway?",
    deleteSynthesis: "Delete synthesis",
    deleteSynthesisConfirmation: "Delete this synthesis? This cannot be undone.",
    synthesisDeleted: "Synthesis deleted.",
    synthesisDeleteFailed: "Synthesis delete failed.",
    exportSynthesisMarkdown: "Export synthesis Markdown",
    synthesisExportWarning: "This export includes unsaved changes and is for the current research record only.",
    privateByDefault: "Private by default",
    sortBy: "Sort by",
    sortUpdated: "Recently updated",
    sortReferenceValue: "Reference value",
    sortTransformability: "Transformability",
    sortCopyrightRisk: "Lowest copyright risk",
    sortProductionReadiness: "Production readiness",
    sortTitle: "Title",
    pinReference: "Pin reference",
    unpinReference: "Unpin reference",
    pinned: "Pinned",
    exportMarkdown: "Export Markdown",
    exportJson: "Export JSON",
    dataManagement: "Data management",
    closeDataManagement: "Close data management",
    backupTab: "Backup",
    restoreTab: "Restore",
    fullBackup: "Export full backup",
    exportingBackup: "Exporting backup...",
    includeDevicePreferences: "Include this device's preferences",
    transparentJsonWarning: "Transparent JSON may contain private sources and research notes.",
    chooseBackupFile: "Choose backup file",
    changeBackupFile: "Change file",
    backupFileDetails: "File details",
    backupVersion: "Backup version",
    backupExportedAt: "Exported at",
    previewBackup: "Preview restore",
    previewingBackup: "Previewing...",
    restoreBackup: "Restore data",
    restoringBackup: "Restoring...",
    retryRestore: "Try again",
    restoreDevicePreferences: "Restore this device's preferences",
    confirmOverwrite: "I confirm that backup data will overwrite existing records with the same ID.",
    unsavedDraftRestoreTitle: "Unsaved draft",
    unsavedDraftRestoreBody: "Restoring will discard the current unsaved draft.",
    discardDraftAndRestore: "Discard draft and restore",
    restoreSucceeded: "Research data restored.",
    preferencesRestoreApplied: "Device preferences restored.",
    preferencesRestoreFailed: "Research data restored, but device preferences could not be saved.",
    backupReferences: "References",
    backupSyntheses: "Syntheses",
    backupRelations: "Relations",
    backupHistoricalSnapshots: "Historical snapshots",
    backupIssues: "Validation issues",
    backupCreate: "Create",
    backupOverwrite: "Overwrite",
    backupPreserve: "Preserve",
    backupInvalidJson: "The file is not valid JSON backup data.",
    backupUnsupportedFormat: "This file is not a RefForge Backup.",
    backupUnsupportedVersion: "This backup version is not supported.",
    backupTooLarge: "The backup file or record count exceeds the 5 MB limit.",
    backupValidationFailed: "The backup did not pass integrity validation.",
    backupChanged: "The backup changed after preview. Choose and preview it again.",
    backupPreviewStale: "Research data changed after preview. Preview again.",
    backupOverwriteConfirmationRequired: "Confirm overwriting existing records before restoring.",
    backupRestoreFailed: "Restore did not complete; no partial research data was written.",
    backupDatabaseUnavailable: "Backup service is unavailable. Try again shortly.",
    backupOperationFailed: "The backup operation did not complete. Try again shortly.",
    exportUnavailable: "Select a reference before exporting.",
    inspirationEntryCount: "Structured inspiration entries",
    reviewQueue: "Review queue",
    queueAll: "All references",
    queueIncomplete: "Incomplete",
    queuePinned: "Pinned",
    queueHighValue: "High value",
    queueLowRisk: "Low copyright risk",
    queueProductionReady: "Production ready",
    qualityChecklist: "Quality checklist",
    qualityGuidedEditing: "Completion navigator",
    qualityGuidedPosition: "Current item",
    previousQualityIssue: "Previous item",
    nextQualityIssue: "Next item",
    completeQualityIssue: "Complete",
    qualityTargetMissing: "The matching edit field was not found; your draft is preserved.",
    qualityComplete: "Complete",
    resizeFiltersPanel: "Resize filters panel",
    resizeDetailsPanel: "Resize details panel",
    collapseFiltersPanel: "Collapse filters panel",
    expandFiltersPanel: "Expand filters panel",
    collapseDetailsPanel: "Collapse details panel",
    expandDetailsPanel: "Expand details panel",
    resetPanelWidth: "Double-click to reset width",
    qualityIssueCount: "Incomplete",
    qualityPositiveSignals: "Positive signals",
    qualitySourceGroup: "Source",
    qualitySafetyGroup: "Safety",
    qualityInspirationGroup: "Inspiration",
    qualityScoresGroup: "Scores",
    qualityMissingSite: "Add site",
    qualityMissingAuthor: "Add author",
    qualityMissingLicense: "Confirm license",
    qualityMissingAttribution: "Add attribution",
    qualityMissingAvoidCopying: "Add avoid-copying notes",
    qualityMissingInspirationPoints: "Add inspiration points",
    qualityMissingInspirationEntries: "Add structured inspiration",
    qualityMissingDeconstruction: "Add deconstruction notes",
    qualityMissingTransformation: "Add transformation ideas",
    qualityMissingRating: "Add rating",
    qualityMissingReferenceValue: "Add reference value",
    qualityMissingTransformability: "Add transformability",
    qualityMissingCopyrightRisk: "Add copyright risk",
    qualityMissingProductionReadiness: "Add production readiness",
    qualityBadgeHighValue: "High value",
    qualityBadgeLowRisk: "Low risk",
    qualityBadgeProductionReady: "Production ready",
    qualityBadgeTransformable: "Transformable",
    qualityBadgeAnalyzed: "Analyzed",
    assetCategory: "Asset category",
    allCategories: "All categories",
    publicStatus: "Public status",
    allStatuses: "All statuses",
    qualityStatus: "Quality status",
    allQualityStatuses: "All quality statuses",
    licenseStatus: "License status",
    allLicenses: "All licenses",
    clearFilters: "Clear filters",
    search: "Search",
    searchPlaceholder: "Title, source, tag, note...",
    addReference: "+ Add reference",
    sourceUrl: "Source URL",
    title: "Title",
    site: "Site",
    author: "Author",
    mediaType: "Media type",
    styleTags: "Style tags",
    styleTagsPlaceholder: "pixel, cozy, sci-fi",
    useTags: "Use tags",
    useTagsPlaceholder: "combat feedback, inventory",
    mechanicTags: "Mechanic tags",
    mechanicTagsPlaceholder: "crafting, combat, navigation",
    moodTags: "Mood tags",
    moodTagsPlaceholder: "warm, tense, mysterious",
    visualLanguageTags: "Visual language tags",
    visualLanguageTagsPlaceholder: "silhouette, contrast, material logic",
    inspirationPoints: "Inspiration points",
    inspirationPointsPlaceholder: "Comma-separated useful ideas",
    deconstructionNotes: "Deconstruction notes",
    transformationIdeas: "Transformation ideas",
    avoidCopying: "Avoid copying",
    previewingMetadata: "Previewing...",
    previewMetadata: "Preview metadata",
    savePrivateReference: "Save private reference",
    references: "references",
    safetySummary: "Safety status stays visible before opening details",
    noReferencesMatch: "No references match these filters",
    noReferencesHint: "Clear filters or add a new private reference to continue validation.",
    unknownSource: "Unknown source",
    selectedReference: "Selected reference",
    openSource: "Open source",
    edit: "Edit",
    source: "Source",
    canonicalUrl: "Canonical URL",
    previewUrl: "Preview URL",
    sourceCategory: "Source category",
    classificationAndSafety: "Classification and safety",
    attributionText: "Attribution text",
    inspiration: "Inspiration",
    rating: "Rating",
    scoreSummary: "Score summary",
    referenceValueScore: "Reference value",
    transformabilityScore: "Transformability",
    copyrightRiskScore: "Copyright risk",
    productionReadinessScore: "Production readiness",
    structuredInspiration: "Structured inspiration",
    addInspirationEntry: "+ Add inspiration entry",
    removeInspirationEntry: "Remove entry",
    inspirationObservation: "Observation",
    inspirationPrinciple: "Principle",
    inspirationTransferableIdea: "Transferable idea",
    inspirationOriginalApplication: "Original application",
    inspirationAvoidCopying: "Avoid copying",
    emptyInspirationEntries: "No structured inspiration entries yet.",
    relatedOriginalAsset: "Related original asset",
    saveChanges: "Save changes",
    saving: "Saving...",
    cancel: "Cancel",
    unknown: "Unknown",
    media: "Media",
    license: "License",
    public: "Public",
    defaultAvoidCopying: "Record what exact expression should not be copied.",
    defaultInspiration: "Add concrete principles this reference teaches.",
    deleteReference: "Delete reference",
    deleting: "Deleting...",
    noReferenceSelected: "No reference selected",
    noReferenceHint: "Add or select a reference to review source, safety, and inspiration fields.",
    metadataPreviewSuccess: "Metadata preview ready. Review the fields before saving.",
    metadataPreviewFailure: "Metadata preview failed. You can still save this reference manually.",
    metadataPreviewLoading: "Previewing metadata...",
    seedFallback: "Showing starter examples. Add a private reference to begin using your own dataset.",
    pasteSourceUrl: "Paste a source URL before previewing metadata.",
    metadataPreviewFailedFallback: "Metadata preview failed. You can still save this reference manually.",
    saveFailed: "Save failed. Form contents were preserved.",
    saveFailedShort: "Save failed.",
    savedPrivate: "Reference saved privately by default.",
    editingSelected: "Editing selected reference.",
    editCanceled: "Edit canceled; no changes saved.",
    selectionChanged: "Selection changed; edit draft was closed.",
    selectionHidden: "Selection no longer visible; edit draft was closed.",
    finishSaving: "Finish saving before changing selection.",
    noChanges: "No changes to save.",
    savingChanges: "Saving reference changes...",
    starterUpdatedLocally: "Starter example updated locally; D1 was not changed.",
    changesSaved: "Reference changes saved.",
    updateFailed: "Update failed. Edit contents were preserved.",
    deleteFailed: "Delete failed.",
    deleted: "Reference deleted.",
  },
} satisfies Record<Language, Record<string, string>>;

export function uiCopy(language: Language = "zh") {
  return copy[language];
}

export function labelForAssetCategory(value: AssetCategory, language: Language = "zh") {
  return assetCategoryLabels[language][value];
}

export function labelForMediaType(value: MediaType, language: Language = "zh") {
  return mediaTypeLabels[language][value];
}

export function labelForLicenseStatus(value: LicenseStatus, language: Language = "zh") {
  return licenseStatusLabels[language][value];
}

export function labelForPublicStatus(value: PublicStatus, language: Language = "zh") {
  return publicStatusLabels[language][value];
}

export function labelForQualityStatus(value: QualityStatus, language: Language = "zh") {
  return qualityStatusLabels[language][value];
}

export type SynthesisErrorCode =
  | "validation"
  | "reference_not_found"
  | "relation_not_found"
  | "reference_unavailable"
  | "not_found"
  | "migration_required"
  | "operation_failed";

export function synthesisErrorMessage(
  code: SynthesisErrorCode | string | undefined,
  language: Language = "zh",
) {
  const copy = uiCopy(language);
  switch (code) {
    case "validation":
      return copy.synthesisValidationFailed;
    case "reference_not_found":
      return copy.synthesisReferencesChanged;
    case "relation_not_found":
      return copy.synthesisRelationNotFound;
    case "reference_unavailable":
      return copy.synthesisReferenceUnavailable;
    case "not_found":
      return copy.synthesisNotFound;
    case "migration_required":
      return copy.synthesisMigrationRequired;
    case "operation_failed":
    default:
      return copy.synthesisOperationFailed;
  }
}

export type BackupErrorCode =
  | "invalid_json"
  | "unsupported_format"
  | "unsupported_version"
  | "backup_too_large"
  | "validation_failed"
  | "backup_changed"
  | "preview_stale"
  | "overwrite_confirmation_required"
  | "restore_failed"
  | "database_unavailable"
  | "backup_operation_failed";

export function backupErrorMessage(
  code: BackupErrorCode | string | undefined,
  language: Language = "zh",
) {
  const copy = uiCopy(language);
  switch (code) {
    case "invalid_json":
      return copy.backupInvalidJson;
    case "unsupported_format":
      return copy.backupUnsupportedFormat;
    case "unsupported_version":
      return copy.backupUnsupportedVersion;
    case "backup_too_large":
      return copy.backupTooLarge;
    case "validation_failed":
      return copy.backupValidationFailed;
    case "backup_changed":
      return copy.backupChanged;
    case "preview_stale":
      return copy.backupPreviewStale;
    case "overwrite_confirmation_required":
      return copy.backupOverwriteConfirmationRequired;
    case "database_unavailable":
      return copy.backupDatabaseUnavailable;
    case "backup_operation_failed":
      return copy.backupOperationFailed;
    case "restore_failed":
      return copy.backupRestoreFailed;
    default:
      return copy.backupOperationFailed;
  }
}

export function labelForSynthesisStatus(value: SynthesisStatus, language: Language = "zh") {
  return synthesisStatusLabels[language][value];
}
