import { integer, sqliteTable, text } from "drizzle-orm/sqlite-core";

export const references = sqliteTable("references", {
  id: text("id").primaryKey(),
  title: text("title").notNull(),
  sourceUrl: text("source_url").notNull(),
  canonicalUrl: text("canonical_url"),
  siteName: text("site_name"),
  author: text("author"),
  previewUrl: text("preview_url"),
  mediaType: text("media_type").notNull(),
  assetCategory: text("asset_category").notNull(),
  sourceCategory: text("source_category"),
  styleTags: text("style_tags").notNull().default("[]"),
  useTags: text("use_tags").notNull().default("[]"),
  mechanicTags: text("mechanic_tags").notNull().default("[]"),
  moodTags: text("mood_tags").notNull().default("[]"),
  visualLanguageTags: text("visual_language_tags").notNull().default("[]"),
  licenseStatus: text("license_status").notNull(),
  attributionText: text("attribution_text"),
  publicStatus: text("public_status").notNull(),
  qualityStatus: text("quality_status").notNull().default("captured"),
  rating: integer("rating"),
  referenceValueScore: integer("reference_value_score"),
  transformabilityScore: integer("transformability_score"),
  copyrightRiskScore: integer("copyright_risk_score"),
  productionReadinessScore: integer("production_readiness_score"),
  inspirationPoints: text("inspiration_points").notNull().default("[]"),
  inspirationEntries: text("inspiration_entries").notNull().default("[]"),
  deconstructionNotes: text("deconstruction_notes"),
  transformationIdeas: text("transformation_ideas"),
  avoidCopyingNotes: text("avoid_copying_notes"),
  relatedOriginalAsset: text("related_original_asset"),
  createdAt: text("created_at").notNull(),
  updatedAt: text("updated_at").notNull(),
});

